# Generated by Django 4.2.21 on 2025-05-15 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("frontendhome", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutoPushSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frequency", models.CharField(default="daily", max_length=20)),
                ("codes_per_day", models.PositiveSmallIntegerField()),
                ("push_time", models.TimeField()),
                (
                    "auto_push_duration",
                    models.PositiveSmallIntegerField(
                        help_text="Duration in days (3 to 7)"
                    ),
                ),
                ("code_type", models.CharField(max_length=50)),
                (
                    "code_complexity",
                    models.PositiveSmallIntegerField(
                        help_text="1 (simple) to 100 (complex)"
                    ),
                ),
                ("code_style", models.CharField(max_length=50)),
                ("default_commit_msg", models.CharField(max_length=255)),
                ("preferred_language", models.CharField(max_length=50)),
                ("preferred_framework", models.CharField(max_length=50)),
                ("comment_style", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auto_push_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
