# Generated by Django 4.2.21 on 2025-05-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontendhome", "0002_autopushsettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autopushsettings",
            name="push_time",
            field=models.CharField(help_text="HH:MM format", max_length=5),
        ),
    ]
