# Generated by Django 4.2.21 on 2025-05-17 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("frontendhome", "0003_alter_autopushsettings_push_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutoPushToggle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auto_push_toggle",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
